# Python Pandas Data Series

In [1]:
import pandas as pd
import numpy as np

1. Write a Pandas program to create and display a one-dimensional array-like object containing an array of data using Pandas module.

In [2]:
ser = pd.Series([1, 2, 3, 4, 5])
ser

0    1
1    2
2    3
3    4
4    5
dtype: int64

2. Write a Pandas program to convert a Panda module Series to Python list and it's type. Go to the 

In [3]:
# py_list = list(ser)

py_list = ser.tolist()
print(type(py_list), py_list)

<class 'list'> [1, 2, 3, 4, 5]


3. Write a Pandas program to add, subtract, multiple and divide two Pandas Series.

In [4]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([6, 7, 8, 9, 10])

add = ser1 + ser2
sub = ser1 - ser2
mut = ser1 * ser2
div = ser1 / ser2

print(add)
print(sub)
print(mut)
print(div)

0     7
1     9
2    11
3    13
4    15
dtype: int64
0   -5
1   -5
2   -5
3   -5
4   -5
dtype: int64
0     6
1    14
2    24
3    36
4    50
dtype: int64
0    0.166667
1    0.285714
2    0.375000
3    0.444444
4    0.500000
dtype: float64


4. Write a Pandas program to compare the elements of the two Pandas Series. Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]

In [5]:
ser1 = [2, 4, 6, 8, 10]
ser2 = [1, 3, 5, 7, 10]

print('Equal:', ser1 == ser2)

print('Greater than:', ser1 > ser2)

print('Less than:', ser1 < ser2)

Equal: False
Greater than: True
Less than: False


5. Write a Pandas program to convert a dictionary to a Pandas series.

```Sample Series:
Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
Converted series:
a 100
b 200
c 300
d 400
e 800```

In [6]:
my_dic = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}

ser = pd.Series(my_dic)
ser

a    100
b    200
c    300
d    400
e    800
dtype: int64

6. Write a Pandas program to convert a NumPy array to a Pandas series.

```Sample Series:
NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0 10
1 20
2 30
3 40
4 50```

In [7]:
arr = np.array([10, 20, 30, 40, 50])

ser = pd.Series(arr)
ser

0    10
1    20
2    30
3    40
4    50
dtype: int64

7. Write a Pandas program to change the data type of given a column or a Series.

```
Sample Series:
Original Data Series:
0 100
1 200
2 python
3 300.12
4 400

Change the said data type to numeric:
0 100.00
1 200.00
2 NaN
3 300.12
4 400.00
dtype: float64
```

In [8]:
ser = pd.Series([100, 200, 'python', 300.12, 400])
print(ser)

ser = pd.to_numeric(ser, errors='coerce')
print(ser)

0       100
1       200
2    python
3    300.12
4       400
dtype: object
0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64


8. Write a Pandas program to convert the first column of a DataFrame as a Series. 

```
Sample Output:
Original DataFrame
col1 col2 col3
0 1 4 7
1 2 5 5
2 3 6 8
3 4 9 12
4 7 5 1
5 11 0 11
1st column as a Series:
0 1
1 2
2 3
3 4
4 7
5 11
Name: col1, dtype: int64
<class 'pandas.core.series.Series'>```

In [9]:
df = pd.DataFrame({'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1,11]})
df

col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

In [10]:
# ser = df.ix[:,0] # deprecated
# ser = df.loc[:,'col1']
ser = df.iloc[:,0]
ser

0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64

9. Write a Pandas program to convert a given Series to an array.

```
Sample Output:
Original Data Series:
0 100
1 200
2 python
3 300.12
4 400
dtype: object
Series to an array
['100' '200' 'python' '300.12' '400']```

In [11]:
ser = pd.Series([100, 200, 'python', 300.12, 400])

# np.array(ser.values.tolist())
# np.array(ser)
ser.values

array([100, 200, 'python', 300.12, 400], dtype=object)

10. Write a Pandas program to convert Series of lists to one Series. 

```Sample Output:
Original Series of list
0 [Red, Green, White]
1 [Red, Black]
2 [Yellow]
dtype: object
One Series
0 Red
1 Green
2 White
3 Red
4 Black
5 Yellow
dtype: object```

In [12]:
ser = pd.Series([['Red', 'Green', 'White'], ['Red', 'Black'], ['Yellow']])
print(ser)

ser.apply(pd.Series).stack().reset_index(drop=True)

0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object


0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object

11. Write a Pandas program to sort a given Series.


```Sample Output:
Original Data Series: 0 100
1 200
2 python
3 300.12
4 400
dtype: object
0 100
1 200
3 300.12
4 400
2 python
dtype: object```

In [13]:
ser = pd.Series(['200', 'python',' 300.12', '400'])
ser.sort_values()

2     300.12
0        200
3        400
1     python
dtype: object

12. Write a Pandas program to add some data to an existing Series.

```
Sample Output:
Original Data Series:
0 100
1 200
2 python
3 300.12
4 400
dtype: object
Data Series after adding some data:
0 100
1 200
2 python
3 300.12
4 400
0 500
1 php
dtype: object
```

In [14]:
ser = pd.Series([100, 200, 'python', 300.12, 400])

# ser[5] = 500
# ser[6] = 'php'

ser = ser.append(pd.Series([500, 'php']))

ser

0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object

13. Write a Pandas program to create a subset of a given series based on value and condition.

```
Sample Output:
Original Data Series:
0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 10
dtype: int64
Subset of the above Data Series:
0 0
1 1
2 2
3 3
4 4
5 5
dtype: int64
```

In [15]:
ser = pd.Series(np.arange(0, 11))

ser = ser[ser < 6]
ser

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

14. Write a Pandas program to change the order of index of a given series.

```
Sample Output:
Original Data Series:
A 1
B 2
C 3
D 4
E 5
dtype: int64
Data Series after changing the order of index:
B 2
A 1
C 3
D 4
E 5
dtype: int64
```

In [16]:
ser = pd.Series(np.arange(1, 6), index=['A', 'B', 'C', 'D', 'E'])

ser = ser.reindex(
    index = ['B', 'A', 'C', 'D', 'E'], ) # return series with index changed

ser

B    2
A    1
C    3
D    4
E    5
dtype: int64

15. Write a Pandas program to create the mean and standard deviation of the data of a given Series. 

```
Sample Output:
Original Data Series:
0 1
1 2
2 3
3 4
4 5
5 6
6 7
7 8
8 9
9 5
10 3
dtype: int64
Mean of the said Data Series:
4.818181818181818
Standard deviation of the said Data Series:
2.522624895547565
```

In [17]:
ser = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 5, 3])

mean = ser.mean()
std = ser.std()

print('Mean:', mean)
print('Std:', std)

Mean: 4.818181818181818
Std: 2.522624895547565


16. Write a Pandas program to get the items of a given series not present in another given series.

```
Sample Output:
Original Series:
sr1:
0 1
1 2
2 3
3 4
4 5
dtype: int64
sr2:
0 2
1 4
2 6
3 8
4 10
dtype: int64
Items of sr1 not present in sr2:
0 1
2 3
4 5
dtype: int64
```

In [18]:
ser1 = pd.Series(np.arange(1, 6))
ser2 = pd.Series(np.arange(2, 11, 2))

ser = ser1[~ser1.isin(ser2)]
ser

0    1
2    3
4    5
dtype: int64

17. Write a Pandas program to get the items which are not common of two given series.

```
Sample Output:
Original Series:
sr1:
0 1
1 2
2 3
3 4
4 5
dtype: int64
sr2:
0 2
1 4
2 6
3 8
4 10
dtype: int64
Items of a given series not present in another given series:
0 1
2 3
4 5
5 6
6 8
7 10
dtype: int64
```

In [19]:
ser1 = pd.Series(np.arange(1, 6))
ser2 = pd.Series(np.arange(2, 11, 2))

# My way
# ser = ser1[~ser1.isin(ser2)].append(ser2[~ser2.isin(ser1)])
# ser

# Union: tarteeb se likhna
sr11 = pd.Series(np.union1d(ser1, ser2)) 
# Intersection: Common element nikalna
sr22 = pd.Series(np.intersect1d(ser1, ser2))
result = sr11[~sr11.isin(sr22)]
result

0     1
2     3
4     5
5     6
6     8
7    10
dtype: int64

18. Write a Pandas program to compute the minimum, 25th percentile, median, 75th, and maximum of a given series.
```
Sample Output:
Original Series:
0 3.000938
1 11.370722
2 14.612143
3 8.990256
4 13.925283
5 12.056875
.... 17 14.118931
18 8.247458
19 5.526727
dtype: float64
Minimum, 25th percentile, median, 75th, and maximum of a given series:
[ 3.00093811 8.09463867 10.23353705 12.21537733 14.61214321]
```

In [20]:
ser = pd.Series([3.000938, 11.370722, 14.612143, 8.990256, 13.925283, 12.056875])

# ans = ser.describe()
# print(ans[3:])

result = np.percentile(ser, q=[0, 25, 50, 75, 100])
result

array([ 3.000938 ,  9.5853725, 11.7137985, 13.458181 , 14.612143 ])

19. Write a Pandas program to calculate the frequency counts of each unique value of a given series.

```
Sample Output:
Original Series:
0 1
1 7
2 1
3 6
4 9
5 1
... 29 2
30 9
31 1
32 2
33 9
34 2
35 9
36 0
37 0
38 4
39 8
dtype: object
Frequency of each unique value of the said series.
0 9
2 7
9 6
1 5
6 3
8 3
7 3
3 2
4 1
5 1
dtype: int64
```

In [21]:
num_series = pd.Series(np.take(list('0123456789'), np.random.randint(10, size=40)))

num_series.value_counts()

6    7
2    6
8    5
9    5
0    4
7    4
4    4
5    3
3    1
1    1
dtype: int64

20. Write a Pandas program to display most frequent value in a given series and replace everything else as 'Other' in the series.

```
Sample Output:
Original Series:
0 3
1 1
2 1
3 3
4 2
5 2
6 1
7 2
8 3
9 1
10 2
11 2
12 2
13 3
14 3
dtype: int64
Top 2 Freq: 2 6
3 5
1 4
dtype: int64
0 Other
1 Other
2 Other
3 Other
4 2
5 2
6 Other
7 2
8 Other
9 Other
10 2
11 2
12 2
13 Other
14 Other
dtype: object
```

In [22]:
ser = pd.Series(np.random.randint(0, 15, [15]))
ser = ser.value_counts()
ser

6     4
1     3
10    3
4     2
2     1
5     1
12    1
dtype: int64

21. Write a Pandas program to find the positions of numbers that are multiples of 5 of a given series.

```
Sample Output:
Original Series:
0 1
1 9
2 8
3 6
4 9
5 7
6 1
7 1
8 1
dtype: int64
Positions of numbers that are multiples of 5:
[]```

In [23]:
ser = pd.Series(np.random.randint(1, 10, 9))

# My way
# ser[ser%5==0]

result = np.argwhere(np.array(ser%5==0))
print(result)

[[4]
 [8]]


In [24]:
type(np.array(ser%5==0))

numpy.ndarray

22. Write a Pandas program to extract items at given positions of a given series.

```
Sample Output:
Original Series:
0 2
1 3
2 9
3 0
4 2
5 3
... 19 0
20 2
21 3
dtype: object
Extract items at given positions of the said series:
0 2
2 9
6 8
11 0
21 3
dtype: object```

In [25]:
ser = pd.Series(np.random.randint(0, 19, [22]))

ser[[0, 2, 6, 11, 21]]

0      7
2     18
6      1
11    11
21     9
dtype: int64

23. Write a Pandas program to get the positions of items of a given series in another given series. 

```
Sample Output:
Original Series:
0 1
1 2
2 3
3 4
4 5
5 6
6 7
7 8
8 9
9 10
dtype: int64
0 1
1 3
2 5
3 7
4 10
dtype: int64
Positions of items of series2 in series1:
[0, 2, 4, 6, 9] ```

In [26]:
ser1 = pd.Series(np.arange(1, 11))
ser2 = pd.Series([1, 3, 5, 7, 10])

res = [pd.Index(ser1).get_loc(i) for i in ser2]
res

[0, 2, 4, 6, 9]

24. Write a Pandas program convert the first and last character of each word to upper case in each word of a given series.

```
Sample Output:
Original Series:
0 php
1 python
2 java
3 c#
dtype: object
First and last character of each word to upper case:
0 PhP
1 PythoN
2 JavA
3 C#
dtype: object```

In [27]:
ser = pd.Series(['php', 'python', 'java', 'c#'])

# My Way
# ser = pd.Series([lang[0].upper() + lang[1: -1] + lang[-1].upper() for lang in ser])

ser = ser.map(lambda x: x[0].upper() + x[1:-1] + x[-1].upper())
ser

0       PhP
1    PythoN
2      JavA
3        C#
dtype: object

25. Write a Pandas program to calculate the number of characters in each word in a given series.

```
Sample Output:
Original Series:
0 Php
1 Python
2 Java
3 C#
dtype: object
Number of characters in each word in the said series:
0 3
1 6
2 4
3 2
dtype: int64```

In [28]:
ser = pd.Series(['php', 'python', 'java', 'c#'])
no_char_in_ser = ser.map(lambda x: len(x))
no_char_in_ser

0    3
1    6
2    4
3    2
dtype: int64

26. Write a Pandas program to compute difference of differences between consecutive numbers of a given series.

```
Sample Output:
Original Series:
0 1
1 3
2 5
3 8
4 10
5 11
6 15
dtype: int64
Difference of differences between consecutive numbers of the said series:
[nan, 2.0, 2.0, 3.0, 2.0, 1.0, 4.0]
[nan, nan, 0.0, 1.0, -1.0, -1.0, 3.0]
```

In [29]:
ser = pd.Series([1, 3, 5, 8, 10, 11, 15])

l1 = ser.diff().to_list()
l2 = ser.diff().diff().to_list()

print(l1)
print(l2)

[nan, 2.0, 2.0, 3.0, 2.0, 1.0, 4.0]
[nan, nan, 0.0, 1.0, -1.0, -1.0, 3.0]


27. Write a Pandas program to convert a series of date strings to a timeseries.

```
Sample Output:
Original Series:
0 01 Jan 2015
1 10-02-2016
2 20180307
3 2014/05/06
4 2016-04-12
5 2019-04-06T11:20
dtype: object
Series of date strings to a timeseries:
0 2015-01-01 00:00:00
1 2016-10-02 00:00:00
2 2018-03-07 00:00:00
3 2014-05-06 00:00:00
4 2016-04-12 00:00:00
5 2019-04-06 11:20:00
dtype: datetime64[ns]
```

In [30]:
ser = pd.Series(['01 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12', '2019-04-06T11:20'])

ser = pd.to_datetime(ser)
ser

0   2015-01-01 00:00:00
1   2016-10-02 00:00:00
2   2018-03-07 00:00:00
3   2014-05-06 00:00:00
4   2016-04-12 00:00:00
5   2019-04-06 11:20:00
dtype: datetime64[ns]

28. Write a Pandas program to get the day of month, day of year, week number and day of week from a given series of date strings.

```
Sample Output:
Original Series:
0 01 Jan 2015
1 10-02-2016
2 20180307
3 2014/05/06
4 2016-04-12
5 2019-04-06T11:20
dtype: object
Day of month:
[1, 2, 7, 6, 12, 6]
Day of year:
[1, 276, 66, 126, 103, 96]
Week number:
[1, 39, 10, 19, 15, 14]
Day of week:
['Thursday', 'Sunday', 'Wednesday', 'Tuesday', 'Tuesday', 'Saturday']
```

In [31]:
ser = pd.Series(['01 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12', '2019-04-06T11:20'])

# ser = pd.to_datetime(ser)
# day = ser.dt.day.to_list()
# year = ser.dt.dayofyear.to_list()
# week = ser.dt.weekofyear.to_list()

from dateutil.parser import parse

ser = ser.map(lambda x: parse(x))
days = ser.dt.day.to_list()
years = ser.dt.dayofyear.to_list()
weeks = ser.dt.isocalendar().week.to_list()
dayname = ser.dt.day_name().to_list()

print(days)
print(years)
print(weeks)
print(dayname)

[1, 2, 7, 6, 12, 6]
[1, 276, 66, 126, 103, 96]
[1, 39, 10, 19, 15, 14]
['Thursday', 'Sunday', 'Wednesday', 'Tuesday', 'Tuesday', 'Saturday']


29. Write a Pandas program to convert year-month string to dates adding a specified day of the month.

```
Sample Output:
Original Series:
0 Jan 2015
1 Feb 2016
2 Mar 2017
3 Apr 2018
4 May 2019
dtype: object
New dates:
0 2015-01-11
1 2016-02-11
2 2017-03-11
3 2018-04-11
4 2019-05-11
dtype: datetime64[ns]
```

In [32]:
ser = pd.Series(['Jan 2015', 'Feb 2016', 'Mar 2017', 'Apr 2018', 'May 2019'])

ser = pd.to_datetime('11' + ser)
ser

0   2015-01-11
1   2016-02-11
2   2017-03-11
3   2018-04-11
4   2019-05-11
dtype: datetime64[ns]

30. Write a Pandas program to filter words from a given series that contain atleast two vowels.

```
Sample Output:
Original Series:
0 Red
1 Green
2 Orange
3 Pink
4 Yellow
5 White
dtype: object
Filtered words:
1 Green
2 Orange
4 Yellow
5 White
dtype: object
```

In [33]:
ser = pd.Series(['Red', 'Green', 'Orange', 'Pink', 'Yellow', 'White'])
mask = []

# vowels = 'aeiou'
# count = 0

# for text in ser: 
#     for t in text:
#         if t.lower() in list(vowels):
#             count += 1
#     if count > 1:
#         mask.append(True)
#     else:
#         mask.append(False)
#     count = 0

# ser[mask]

from collections import Counter
mask = ser.map(lambda c: sum([Counter(c.lower()).get(i, 0) for i in list('aeiou')]) >= 2)
print(ser[mask])

1     Green
2    Orange
4    Yellow
5     White
dtype: object


31. Write a Pandas program to compute the Euclidean distance between two given series. 

Euclidean distance
From Wikipedia,
In mathematics, the Euclidean distance or Euclidean metric is the "ordinary" straight-line distance between two points in Euclidean space. With this distance, Euclidean space becomes a metric space. The associated norm is called the Euclidean norm.

```
Sample Output:
Original series:
0 1
1 2
2 3
3 4
4 5
5 6
6 7
7 8
8 9
9 10
dtype: int64
0 11
1 8
2 7
3 5
4 6
5 5
6 3
7 4
8 7
9 1
dtype: int64
Euclidean distance between two said series:
16.492422502470642```

In [34]:
ser1 = pd.Series(np.arange(1, 11))
ser2 = pd.Series([11, 8, 7, 5, 6, 5, 3, 4, 7, 1])

np.linalg.norm(ser1 - ser2)

16.492422502470642

32. Write a Pandas program to find the positions of the values neighboured by smaller values on both sides in a given series.


```
Sample Output:
Original series:
0 1
1 8
2 7
3 5
4 6
5 5
6 3
7 4
8 7
9 1
dtype: int64
Positions of the values surrounded by smaller values on both sides:
[1 4 8]```

In [35]:
ser = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])

# print('ser:', ser.to_list())
# s1 = np.diff(ser)
# print('s1:', s1)
# s2 = np.sign(s1)
# print('s2:', s2)
# s3 = np.diff(s2)
# print('s3:', s3)
# np.where(s3 == -2)[0] + 1

temp = np.diff(np.sign(np.diff(ser)))
positions = np.where(temp == -2)[0] + 1

positions

array([1, 4, 8])

33. Write a Pandas program to replace missing white spaces in a given string with the least frequent character.

```
Sample Output:
Original series:
abc def abcdef icd
c 3
d 3
3
b 2
e 2
a 2
f 2
i 1
dtype: int64
abcidefiabcdefiicd```

In [36]:
string = 'abc def abcdef icd'
ser = pd.Series(list(string))
ele_freq = ser.value_counts()
new_char = ele_freq.index[-1]

new_string = ''.join(ser.replace(' ', new_char))
new_string

'abcidefiabcdefiicd'

34. Write a Pandas program to compute the autocorrelations of a given numeric series. 


From Wikipedia:
Autocorrelation, also known as serial correlation, is the correlation of a signal with a delayed copy of itself as a function of delay. Informally, it is the similarity between observations as a function of the time lag between them.

```
Sample Output:
Original series:
0 13.207262
1 4.098685
2 -1.435534
3 13.626760
... 13 -2.346193
14 17.873884
dtype: float64
Autocorrelations of the said series:
[-0.38, 0.1, -0.43, 0.03, 0.35, -0.2, 0.04, -0.59, 0.34, 0.11]```

In [37]:
ser = pd.Series(np.arange(15) + np.random.normal(1, 10, 15))
autocorr = [ser.autocorr(i) for i in range(11)]
autocorr[1:]

[-0.2795170439461213,
 -0.05336032186154016,
 0.28952429048898504,
 -0.28020472389620815,
 0.07997118762098156,
 -0.21563254769162635,
 -0.23150099080724842,
 -0.6033204893827023,
 -0.06460151800655026,
 0.6167573140490784]

35. Write a Pandas program to create a TimeSeries to display all the Sundays of given year.

```
Sample Output:
All Sundays of 2019:
0 2020-01-05
1 2020-01-12
2 2020-01-19
3 2020-01-26
4 2020-02-02
5 2020-02-09
..... 48 2020-12-06
49 2020-12-13
50 2020-12-20
51 2020-12-27```

In [38]:
ser = pd.Series(pd.date_range('2020-01-01', periods=52, freq='W-SUN'))
ser

0    2020-01-05
1    2020-01-12
2    2020-01-19
3    2020-01-26
4    2020-02-02
5    2020-02-09
6    2020-02-16
7    2020-02-23
8    2020-03-01
9    2020-03-08
10   2020-03-15
11   2020-03-22
12   2020-03-29
13   2020-04-05
14   2020-04-12
15   2020-04-19
16   2020-04-26
17   2020-05-03
18   2020-05-10
19   2020-05-17
20   2020-05-24
21   2020-05-31
22   2020-06-07
23   2020-06-14
24   2020-06-21
25   2020-06-28
26   2020-07-05
27   2020-07-12
28   2020-07-19
29   2020-07-26
30   2020-08-02
31   2020-08-09
32   2020-08-16
33   2020-08-23
34   2020-08-30
35   2020-09-06
36   2020-09-13
37   2020-09-20
38   2020-09-27
39   2020-10-04
40   2020-10-11
41   2020-10-18
42   2020-10-25
43   2020-11-01
44   2020-11-08
45   2020-11-15
46   2020-11-22
47   2020-11-29
48   2020-12-06
49   2020-12-13
50   2020-12-20
51   2020-12-27
dtype: datetime64[ns]

36. Write a Pandas program to convert given series into a dataframe with its index as another column on the dataframe.

```
Sample Output:
index 0
0 A 0
1 B 1
2 C 2
3 D 3
4 E 4```

In [39]:
my_dict = dict(zip(list('ABCDE'), range(8)))
ser = pd.Series(my_dict)
df = ser.to_frame().reset_index()

df

index  0
0     A  0
1     B  1
2     C  2
3     D  3
4     E  4

37. Write a Pandas program to stack two given series vertically and horizontally.

```
Sample Output:
Original Series:
0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
dtype: int64
0 p
1 q
2 r
3 s
4 t
5 u
6 v
7 w
8 x
9 y
dtype: object
Stack two given series vertically and horizontally:
0 1
0 0 p
1 1 q
2 2 r
3 3 s
4 4 t
5 5 u
6 6 v
7 7 w
8 8 x
9 9 y ```

In [40]:
ser1 = pd.Series(np.arange(10))
ser2 = pd.Series(list('pqrstuvwxy'))

pd.concat([ser1, ser2], axis=1)

0  1
0  0  p
1  1  q
2  2  r
3  3  s
4  4  t
5  5  u
6  6  v
7  7  w
8  8  x
9  9  y

38. Write a Pandas program to check the equality of two given series.

```
Sample Output:
Original Series:
0 1
1 8
2 7
3 5
4 6
5 5
6 3
7 4
8 7
9 1
dtype: int64
0 1
1 8
2 7
3 5
4 6
5 5
6 3
7 4
8 7
9 1
dtype: int64
Check 2 series are equal or not?
0 True
1 True
2 True
3 True
4 True
5 True
6 True
7 True
8 True
9 True
dtype: bool```

In [41]:
ser1 = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])
ser2 = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])

ser1 == ser2

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
dtype: bool

39. Write a Pandas program to find the index of the first occurrence of the smallest and largest value of a given series.

```
Sample Output:
Original Series:
0 1
1 3
2 7
3 12
4 88
5 23
6 3
7 1
8 9
9 0
dtype: int64
Index of the first occurrence of the smallest and largest value of the said series:
9
4```

In [42]:
ser = pd.Series([1, 3, 7, 12, 88, 23, 3, 1, 9, 0])

min_val_index = np.argmin(ser)
max_val_index = np.argmax(ser)

print(min_val_index, max_val_index)

9 4


40. Write a Pandas program to check inequality over the index axis of a given dataframe and a given series.

```
Sample Output:
Original DataFrame:
W X Y Z
0 68.0 78.0 84 86
1 75.0 75.0 94 97
2 86.0 NaN 89 96
3 80.0 80.0 86 72
4 NaN 86.0 86 83
Original Series:
0 68.0
1 75.0
2 86.0
3 80.0
4 NaN
dtype: float64
Check for inequality of the said series & dataframe:
W X Y Z
0 False True True True
1 False False True True
2 False True True True
3 False False True True
4 True True True True```

In [43]:
df = pd.DataFrame([[68.0, 78.0, 84, 86], [75.0, 75.0, 94, 97], [86.0, np.nan, 89, 96], [80.0, 80.0, 86, 72], [np.nan, 86.0, 86, 83]], columns=list('WXYZ'))
ser = pd.Series([68.0, 75.0, 86.0, 80.0])

print(df)
print()

print(ser)
print()

df.ne(ser, axis=0)

      W     X   Y   Z
0  68.0  78.0  84  86
1  75.0  75.0  94  97
2  86.0   NaN  89  96
3  80.0  80.0  86  72
4   NaN  86.0  86  83

0    68.0
1    75.0
2    86.0
3    80.0
dtype: float64



W      X     Y     Z
0  False   True  True  True
1  False  False  True  True
2  False   True  True  True
3  False  False  True  True
4   True   True  True  True